import { type NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/Navbar";
import { Header } from "../components/sections/home/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />
        <Header />
      </main>
    </>
  );
};

export default Home;
